apiVersion: v1
kind: Pod
metadata:
  name: conjur-oss
spec:
  containers:
  - image: docker.io/postgres:latest
    name: database
    env:
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    ports:
    - containerPort: 5432
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: conjur-data
  - image: docker.io/cyberark/conjur:latest
    name: conjur
    args:
    - server
    env:
    - name: DATABASE_URL
      value: postgres://postgres@localhost/postgres
    - name: CONJUR_DATA_KEY
      value: <conjur-data-key>
    - name: CONJUR_AUTHENTICATORS
      value: authn,authn-k8s/demo,authn-jwt/jenkins
    ports:
    - containerPort: 80
      hostPort: 80
  - image: docker.io/nginx:latest
    name: proxy
    ports:
    - containerPort: 443
      hostPort: 443
    volumeMounts:
    - mountPath: /etc/nginx/conf.d
      name: nginx-conf
    - mountPath: /etc/nginx/tls
      name: nginx-tls
  volumes:
  - name: nginx-conf
    hostPath:
      path: /opt/conjur/conf
      type: Directory
  - name: nginx-tls
    hostPath:
      path: /opt/conjur/conf/tls
      type: Directory
  - name: conjur-data
    hostPath:
      path: /opt/conjur/data
      type: Directory